# Generated by Django 5.2.1 on 2026-04-22 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_category_id_alter_comment_id_alter_person_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
